// ignore: constant_identifier_names
const List<String> categories_en = [
  /* 0 */ 'Virtues Of Supplication',
  /* 1 */ 'Virtues Of Zikr',
  /* 2 */ 'Etiquette Of Supplication',
  /* 3 */ 'Etiquette Of Zikr',
  /* 4 */ 'Times Of Positive Response',
  /* 5 */ 'Conditions Conducive To Positive Response',
  /* 6 */ 'Places Where Supplication Is Accepted',
  /* 7 */ 'Those Whose Supplication Is Accepted',
  /* 8 */ 'The Greatest Name Of Allah',
  /* 9 */ 'The Beautiful Names Of Allah',
  /* 10 */ 'Some More Forms Of Zikr',
  /* 11 */ 'When Supplication Is Granted',
  /* 12 */ 'Supplication For Morning And Evening',
  /* 13 */ 'Evening Only',
  /* 14 */ 'Morning Only',
  /* 15 */ 'When the Sun Rises',
  /* 16 */ 'Supplication for Day time',
  /* 17 */ 'When Adhan for Magrib is called',
  /* 18 */ 'Supplication for Night time',
  /* 19 */ 'Supplication for Day or Night',
  /* 20 */ 'Supplication On Entering Home',
  /* 21 */ 'When Darkness Of Night Spreads',
  /* 22 */ 'When Going to Sleep',
];
